export const types = Object.freeze({
  WEATHER_START_FETCHING: "WEATHER_START_FETCHING",
  WEATHER_STOP_FETCHING: "WEATHER_STOP_FETCHING",
  WEATHER_SET_FETCHING_ERROR: "WEATHER_SET_FETCHING_ERROR",
  WEATHER_SELECT_DAY: "WEATHER_SELECT_DAY",
  WEATHER_FILL_DAYS: "WEATHER_FILL_DAYS",
  WEATHER_FILTER: "WEATHER_FILTER",
});
